import { defineConfig } from "tinacms";

// Your hosting provider likely exposes this as an environment variable
const branch =
  process.env.GITHUB_BRANCH ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  process.env.HEAD ||
  "main";

export default defineConfig({
  branch,

  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,

  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "images",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "siteSettings",
        label: "Nastavenia webu",
        path: "content/site",
        format: "json",
        match: {
          include: "site-settings",
        },
        fields: [
          {type: "image", name: "logoImage", label: "Logo"},
          {type: "string", name: "logoAlt", label: "Alt loga"},
          {type: "string", name: "logoText", label: "Text pri logu"},
          {
            type: "object",
            name: "navLinks",
            label: "Menu",
            list: true,
            fields: [
              {type: "string", name: "label", label: "Text"},
              {type: "string", name: "href", label: "Odkaz"},
            ],
          },
          {
            type: "object",
            name: "contactLink",
            label: "Kontakt v menu",
            fields: [
              {type: "string", name: "label", label: "Text"},
              {type: "string", name: "href", label: "Odkaz"},
            ],
          },
          {
            type: "object",
            name: "footerLinks",
            label: "Footer odkazy",
            list: true,
            fields: [
              {type: "string", name: "label", label: "Text"},
              {type: "string", name: "href", label: "Odkaz"},
            ],
          },
          {type: "string", name: "footerCopyright", label: "Footer copyright"},
          {type: "string", name: "footerAddress", label: "Footer adresa"},
          {type: "string", name: "footerCreditLabel", label: "Footer kredit label"},
          {type: "string", name: "footerCreditText", label: "Footer kredit text"},
          {type: "string", name: "footerCreditHref", label: "Footer kredit odkaz"},
        ],
        ui: {
          allowedActions: {create: false, delete: false},
        },
      },
      {
        name: "references",
        label: "Referencie",
        path: "content/site",
        format: "json",
        match: {
          include: "references",
        },
        fields: [
          {type: "string", name: "tag", label: "Nadpis sekcie"},
          {
            type: "object",
            name: "items",
            label: "Logá",
            list: true,
            fields: [
              {type: "string", name: "alt", label: "Alt text"},
              {type: "image", name: "src", label: "Obrázok"},
            ],
          },
        ],
        ui: {
          allowedActions: {create: false, delete: false},
        },
      },
      {
        name: "homePage",
        label: "Domovská stránka",
        path: "content/pages",
        format: "json",
        match: {
          include: "home",
        },
        fields: [
          {type: "string", name: "heroEyebrow", label: "Hero horný text"},
          {type: "string", name: "heroTitleLine1", label: "Hero riadok 1"},
          {type: "string", name: "heroTitleLine2", label: "Hero riadok 2"},
          {type: "string", name: "heroTitleAccent", label: "Hero zvýraznenie"},
          {type: "string", name: "heroSubtitle", label: "Hero podnadpis"},
          {type: "string", name: "heroDescription", label: "Hero popis", ui: {component: "textarea"}},
          {type: "string", name: "heroPrimaryLabel", label: "Primárne tlačidlo text"},
          {type: "string", name: "heroPrimaryHref", label: "Primárne tlačidlo odkaz"},
          {type: "string", name: "heroSecondaryLabel", label: "Sekundárne tlačidlo text"},
          {type: "string", name: "heroSecondaryHref", label: "Sekundárne tlačidlo odkaz"},
          {type: "image", name: "heroBackgroundImage", label: "Hero pozadie"},
          {type: "image", name: "heroProductImage", label: "Hero produktový obrázok"},
          {
            type: "object",
            name: "heroStats",
            label: "Hero štatistiky",
            list: true,
            fields: [
              {type: "string", name: "value", label: "Hodnota"},
              {type: "string", name: "label", label: "Popis"},
            ],
          },
          {type: "string", name: "servicesTag", label: "Služby tag"},
          {type: "string", name: "servicesTitle", label: "Služby nadpis"},
          {type: "string", name: "servicesDescription", label: "Služby popis", ui: {component: "textarea"}},
          {
            type: "object",
            name: "services",
            label: "Služby",
            list: true,
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
              {type: "string", name: "buttonLabel", label: "Text tlačidla"},
              {type: "string", name: "buttonHref", label: "Odkaz tlačidla"},
              {type: "image", name: "image", label: "Obrázok"},
              {type: "string", name: "imageAlign", label: "Obrázok vľavo/vpravo"},
              {type: "string", name: "imageFit", label: "Contain alebo cover"},
            ],
          },
          {type: "string", name: "extrasTag", label: "Extras tag"},
          {type: "string", name: "extrasTitle", label: "Extras nadpis"},
          {type: "string", name: "extras", label: "Extras položky", list: true},
          {type: "string", name: "aboutTag", label: "O firme tag"},
          {type: "string", name: "aboutTitle", label: "O firme nadpis"},
          {type: "string", name: "aboutText", label: "O firme text", ui: {component: "textarea"}},
          {type: "image", name: "aboutImage", label: "O firme obrázok"},
          {type: "string", name: "aboutIcoLabel", label: "IČO label"},
          {type: "string", name: "aboutIcoValue", label: "IČO hodnota"},
          {type: "string", name: "aboutDicLabel", label: "DIČ label"},
          {type: "string", name: "aboutDicValue", label: "DIČ hodnota"},
          {type: "string", name: "aboutAddressLabel", label: "Adresa label"},
          {type: "string", name: "aboutAddressValue", label: "Adresa hodnota"},
          {type: "string", name: "ctaTitle", label: "CTA nadpis"},
          {type: "string", name: "ctaText", label: "CTA text", ui: {component: "textarea"}},
          {type: "string", name: "ctaButtonLabel", label: "CTA tlačidlo text"},
          {type: "string", name: "ctaButtonHref", label: "CTA tlačidlo odkaz"},
        ],
        ui: {
          allowedActions: {create: false, delete: false},
          router: () => "/",
        },
      },
      {
        name: "kontaktPage",
        label: "Kontakt",
        path: "content/pages",
        format: "json",
        match: {
          include: "kontakt",
        },
        fields: [
          {type: "string", name: "heroTag", label: "Hero tag"},
          {type: "string", name: "heroTitle", label: "Hero nadpis"},
          {type: "string", name: "heroDescription", label: "Hero popis", ui: {component: "textarea"}},
          {type: "string", name: "personLabel", label: "Kontaktná osoba label"},
          {type: "string", name: "personValue", label: "Kontaktná osoba hodnota"},
          {type: "string", name: "addressLabel", label: "Adresa label"},
          {type: "string", name: "addressLines", label: "Riadky adresy", list: true},
          {type: "string", name: "phoneLabel", label: "Telefón label"},
          {type: "string", name: "phoneValue", label: "Telefón hodnota"},
          {type: "string", name: "phoneHref", label: "Telefón odkaz"},
          {type: "string", name: "emailLabel", label: "Email label"},
          {type: "string", name: "emailValue", label: "Email hodnota"},
          {type: "string", name: "emailHref", label: "Email odkaz"},
          {type: "string", name: "webLabel", label: "Web label"},
          {type: "string", name: "webValue", label: "Web hodnota"},
          {type: "string", name: "webHref", label: "Web odkaz"},
          {type: "string", name: "companyTag", label: "Firemné údaje nadpis"},
          {
            type: "object",
            name: "companyFacts",
            label: "Firemné údaje",
            list: true,
            fields: [
              {type: "string", name: "label", label: "Label"},
              {type: "string", name: "value", label: "Hodnota"},
            ],
          },
          {type: "string", name: "formTitle", label: "Nadpis formulára"},
          {type: "string", name: "firstNameLabel", label: "Meno label"},
          {type: "string", name: "firstNamePlaceholder", label: "Meno placeholder"},
          {type: "string", name: "phoneFieldLabel", label: "Telefón label vo formulári"},
          {type: "string", name: "phoneFieldPlaceholder", label: "Telefón placeholder"},
          {type: "string", name: "emailFieldLabel", label: "Email label vo formulári"},
          {type: "string", name: "emailFieldPlaceholder", label: "Email placeholder"},
          {type: "string", name: "interestLabel", label: "Oblasť záujmu label"},
          {type: "string", name: "interestPlaceholder", label: "Oblasť záujmu placeholder"},
          {type: "string", name: "interestOptions", label: "Možnosti", list: true},
          {type: "string", name: "messageLabel", label: "Správa label"},
          {type: "string", name: "messagePlaceholder", label: "Správa placeholder"},
          {type: "string", name: "submitLabel", label: "Tlačidlo"},
        ],
        ui: {
          allowedActions: {create: false, delete: false},
          router: () => "/kontakt",
        },
      },
      {
        name: "paletyPage",
        label: "Palety",
        path: "content/pages",
        format: "json",
        match: {
          include: "palety",
        },
        fields: [
          {type: "string", name: "heroTag", label: "Hero tag"},
          {type: "string", name: "heroTitle", label: "Hero nadpis"},
          {type: "string", name: "heroDescription", label: "Hero popis", ui: {component: "textarea"}},
          {type: "string", name: "nonRobotTag", label: "Nerobotické tag"},
          {type: "string", name: "nonRobotTitle", label: "Nerobotické nadpis"},
          {type: "string", name: "nonRobotDescription", label: "Nerobotické popis", ui: {component: "textarea"}},
          {type: "string", name: "nonRobotButtonLabel", label: "Nerobotické tlačidlo text"},
          {type: "string", name: "nonRobotButtonHref", label: "Nerobotické tlačidlo odkaz"},
          {type: "image", name: "nonRobotImage", label: "Nerobotické obrázok"},
          {type: "string", name: "nonRobotImageAlt", label: "Nerobotické alt"},
          {type: "string", name: "nonRobotCardTitle", label: "Nerobotické card title"},
          {type: "string", name: "nonRobotCardDescription", label: "Nerobotické card popis"},
          {type: "string", name: "robotTag", label: "Robotické tag"},
          {type: "string", name: "robotTitle", label: "Robotické nadpis"},
          {type: "string", name: "robotDescription", label: "Robotické popis", ui: {component: "textarea"}},
          {type: "string", name: "robotItems", label: "Robotické položky", list: true},
          {type: "string", name: "robotButtonLabel", label: "Robotické tlačidlo text"},
          {type: "string", name: "robotButtonHref", label: "Robotické tlačidlo odkaz"},
          {type: "image", name: "robotImage", label: "Robotické obrázok"},
          {type: "string", name: "robotImageAlt", label: "Robotické alt"},
          {type: "string", name: "robotCardTitle", label: "Robotické card title"},
          {type: "string", name: "robotCardDescription", label: "Robotické card popis"},
          {type: "string", name: "ctaTitle", label: "CTA nadpis"},
          {type: "string", name: "ctaText", label: "CTA text", ui: {component: "textarea"}},
          {type: "string", name: "ctaButtonLabel", label: "CTA tlačidlo text"},
          {type: "string", name: "ctaButtonHref", label: "CTA tlačidlo odkaz"},
        ],
        ui: {
          allowedActions: {create: false, delete: false},
          router: () => "/palety",
        },
      },
      {
        name: "zariadeniaPage",
        label: "Zariadenia",
        path: "content/pages",
        format: "json",
        match: {
          include: "zariadenia",
        },
        fields: [
          {type: "string", name: "heroTag", label: "Hero tag"},
          {type: "string", name: "heroTitle", label: "Hero nadpis"},
          {type: "string", name: "heroDescription", label: "Hero popis", ui: {component: "textarea"}},
          {type: "string", name: "casesTag", label: "Referencie tag"},
          {type: "string", name: "casesTitle", label: "Referencie nadpis"},
          {
            type: "object",
            name: "cases",
            label: "Realizácie",
            list: true,
            fields: [
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
              {type: "image", name: "src", label: "Obrázok"},
              {type: "string", name: "alt", label: "Alt"},
            ],
          },
          {type: "string", name: "processTag", label: "Proces tag"},
          {type: "string", name: "processTitle", label: "Proces nadpis"},
          {
            type: "object",
            name: "processSteps",
            label: "Kroky",
            list: true,
            fields: [
              {type: "string", name: "num", label: "Číslo"},
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
            ],
          },
          {type: "string", name: "ctaTitle", label: "CTA nadpis"},
          {type: "string", name: "ctaText", label: "CTA text", ui: {component: "textarea"}},
          {type: "string", name: "ctaButtonLabel", label: "CTA tlačidlo text"},
          {type: "string", name: "ctaButtonHref", label: "CTA tlačidlo odkaz"},
        ],
        ui: {
          allowedActions: {create: false, delete: false},
          router: () => "/zariadenia",
        },
      },
      {
        name: "vyrobaPage",
        label: "Výroba",
        path: "content/pages",
        format: "json",
        match: {
          include: "vyroba",
        },
        fields: [
          {type: "string", name: "heroTag", label: "Hero tag"},
          {type: "string", name: "heroTitle", label: "Hero nadpis"},
          {type: "string", name: "heroDescription", label: "Hero popis", ui: {component: "textarea"}},
          {type: "string", name: "galleryTag", label: "Galéria tag"},
          {type: "string", name: "galleryTitle", label: "Galéria nadpis"},
          {type: "string", name: "galleryDescription", label: "Galéria popis", ui: {component: "textarea"}},
          {
            type: "object",
            name: "images",
            label: "Výrobné priestory",
            list: true,
            fields: [
              {type: "image", name: "src", label: "Obrázok"},
              {type: "string", name: "alt", label: "Alt"},
              {type: "string", name: "title", label: "Nadpis"},
            ],
          },
          {type: "string", name: "servicesTag", label: "Služby tag"},
          {type: "string", name: "servicesTitle", label: "Služby nadpis"},
          {
            type: "object",
            name: "services",
            label: "Služby",
            list: true,
            fields: [
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
            ],
          },
          {type: "string", name: "ctaTitle", label: "CTA nadpis"},
          {type: "string", name: "ctaText", label: "CTA text", ui: {component: "textarea"}},
          {type: "string", name: "ctaButtonLabel", label: "CTA tlačidlo text"},
          {type: "string", name: "ctaButtonHref", label: "CTA tlačidlo odkaz"},
        ],
        ui: {
          allowedActions: {create: false, delete: false},
          router: () => "/vyroba",
        },
      },
      {
        name: "produktyPage",
        label: "Produkty",
        path: "content/pages",
        format: "json",
        match: {
          include: "produkty",
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              {type: "string", name: "eyebrow", label: "Horný text"},
              {type: "string", name: "titleLines", label: "Riadky nadpisu", list: true},
              {type: "string", name: "titleAccent", label: "Zvýraznenie"},
              {type: "string", name: "subtitle", label: "Podnadpis"},
              {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
              {type: "image", name: "backgroundImage", label: "Pozadie"},
              {type: "image", name: "productImage", label: "Produktový obrázok"},
              {type: "string", name: "primaryButtonLabel", label: "Primárne tlačidlo text"},
              {type: "string", name: "primaryButtonHref", label: "Primárne tlačidlo odkaz"},
              {type: "string", name: "secondaryButtonLabel", label: "Sekundárne tlačidlo text"},
              {type: "string", name: "secondaryButtonHref", label: "Sekundárne tlačidlo odkaz"},
              {
                type: "object",
                name: "stats",
                label: "Štatistiky",
                list: true,
                fields: [
                  {type: "string", name: "value", label: "Hodnota"},
                  {type: "string", name: "label", label: "Popis"},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "electricSection",
            label: "Prečo elektrický",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "paragraphs", label: "Odseky", list: true, ui: {component: "textarea"}},
              {
                type: "object",
                name: "efficiency",
                label: "Porovnanie účinnosti",
                list: true,
                fields: [
                  {type: "string", name: "name", label: "Názov"},
                  {type: "string", name: "value", label: "Hodnota"},
                  {type: "string", name: "barWidth", label: "Šírka baru"},
                  {type: "string", name: "variant", label: "Variant"},
                ],
              },
              {
                type: "object",
                name: "statCards",
                label: "Karty štatistík",
                list: true,
                fields: [
                  {type: "string", name: "value", label: "Hodnota"},
                  {type: "string", name: "label", label: "Popis"},
                ],
              },
              {type: "image", name: "image", label: "Obrázok"},
            ],
          },
          {
            type: "object",
            name: "advantagesSection",
            label: "Výhody",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {
                type: "object",
                name: "items",
                label: "Položky",
                list: true,
                fields: [
                  {type: "string", name: "title", label: "Nadpis"},
                  {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "usageSection",
            label: "Použitie",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {
                type: "object",
                name: "items",
                label: "Položky",
                list: true,
                fields: [
                  {type: "string", name: "title", label: "Nadpis"},
                  {type: "string", name: "description", label: "Popis"},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "parametersSection",
            label: "Parametre",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {type: "image", name: "dimensionImages", label: "Rozmerové obrázky", list: true},
              {
                type: "object",
                name: "tabs",
                label: "Záložky",
                fields: [
                  {
                    type: "object",
                    name: "basic",
                    label: "Základné",
                    fields: [
                      {type: "string", name: "label", label: "Label"},
                      {type: "string", name: "columns", label: "Stĺpce", list: true},
                      {
                        type: "object",
                        name: "rows",
                        label: "Riadky",
                        list: true,
                        fields: [
                          {type: "string", name: "label", label: "Parameter"},
                          {type: "string", name: "values", label: "Hodnoty", list: true},
                        ],
                      },
                      {type: "string", name: "footnote", label: "Poznámka"},
                    ],
                  },
                  {
                    type: "object",
                    name: "battery",
                    label: "Batérie",
                    fields: [
                      {type: "string", name: "label", label: "Label"},
                      {type: "string", name: "columns", label: "Stĺpce", list: true},
                      {
                        type: "object",
                        name: "rows",
                        label: "Riadky",
                        list: true,
                        fields: [
                          {type: "string", name: "label", label: "Parameter"},
                          {type: "string", name: "values", label: "Hodnoty", list: true},
                        ],
                      },
                      {type: "image", name: "image", label: "Obrázok"},
                      {type: "string", name: "imageAlt", label: "Alt obrázka"},
                    ],
                  },
                  {
                    type: "object",
                    name: "charging",
                    label: "Nabíjanie",
                    fields: [
                      {type: "string", name: "label", label: "Label"},
                      {
                        type: "object",
                        name: "rows",
                        label: "Riadky",
                        list: true,
                        fields: [
                          {type: "string", name: "label", label: "Parameter"},
                          {type: "string", name: "value", label: "Hodnota"},
                        ],
                      },
                      {type: "image", name: "image", label: "Obrázok"},
                      {type: "string", name: "imageAlt", label: "Alt obrázka"},
                    ],
                  },
                  {
                    type: "object",
                    name: "equipment",
                    label: "Výbava",
                    fields: [
                      {type: "string", name: "label", label: "Label"},
                      {
                        type: "object",
                        name: "groups",
                        label: "Skupiny",
                        list: true,
                        fields: [
                          {type: "string", name: "title", label: "Názov skupiny"},
                          {
                            type: "object",
                            name: "items",
                            label: "Položky",
                            list: true,
                            fields: [
                              {type: "string", name: "label", label: "Názov"},
                              {type: "string", name: "type", label: "Typ"},
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "rangeSection",
            label: "Dojazd",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {
                type: "object",
                name: "cards",
                label: "Karty",
                list: true,
                fields: [
                  {type: "image", name: "src", label: "Obrázok"},
                  {type: "string", name: "label", label: "Nadpis"},
                  {type: "string", name: "badge", label: "Badge"},
                  {type: "string", name: "badgeClass", label: "CSS trieda"},
                  {type: "string", name: "info", label: "Info", ui: {component: "textarea"}},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "accessoriesSection",
            label: "Príslušenstvo",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {
                type: "object",
                name: "items",
                label: "Položky",
                list: true,
                fields: [
                  {type: "image", name: "src", label: "Obrázok"},
                  {type: "string", name: "alt", label: "Alt"},
                  {type: "string", name: "title", label: "Nadpis"},
                  {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "certificationsSection",
            label: "Certifikáty",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {type: "image", name: "images", label: "Obrázky", list: true},
            ],
          },
          {
            type: "object",
            name: "gallerySection",
            label: "Fotogaléria",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "description", label: "Popis"},
              {
                type: "object",
                name: "images",
                label: "Obrázky",
                list: true,
                fields: [
                  {type: "image", name: "src", label: "Obrázok"},
                  {type: "string", name: "alt", label: "Alt"},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "videoSection",
            label: "Videogaléria",
            fields: [
              {type: "string", name: "tag", label: "Tag"},
              {type: "string", name: "title", label: "Nadpis"},
              {
                type: "object",
                name: "videos",
                label: "Videá",
                list: true,
                fields: [
                  {type: "string", name: "id", label: "YouTube ID"},
                  {type: "string", name: "label", label: "Label"},
                ],
              },
            ],
          },
          {
            type: "object",
            name: "pricingSection",
            label: "Cenník CTA",
            fields: [
              {type: "string", name: "title", label: "Nadpis"},
              {type: "string", name: "description", label: "Popis", ui: {component: "textarea"}},
              {type: "string", name: "primaryButtonLabel", label: "Primárne tlačidlo text"},
              {type: "string", name: "primaryButtonHref", label: "Primárne tlačidlo odkaz"},
              {type: "string", name: "secondaryButtonLabel", label: "Sekundárne tlačidlo text"},
              {type: "string", name: "secondaryButtonHref", label: "Sekundárne tlačidlo odkaz"},
            ],
          },
        ],
        ui: {
          allowedActions: {create: false, delete: false},
          router: () => "/produkty",
        },
      },
    ],
  },
});
