import {groq} from 'next-sanity'

const simplePageProjection = `{
  heroTag,
  heroTitle,
  heroDescription,
  sections[]{
    _key,
    tag,
    title,
    description,
    buttonLabel,
    buttonHref,
    image,
    imageAlign,
    imageFit,
    bullets
  },
  galleryTag,
  galleryTitle,
  galleryDescription,
  galleryCards[]{
    _key,
    title,
    description,
    image,
    alt
  },
  processTag,
  processTitle,
  processSteps[]{
    _key,
    number,
    title,
    description
  },
  ctaTitle,
  ctaText,
  ctaButtonLabel,
  ctaButtonHref
}`

export const siteSettingsQuery = groq`*[_type == "siteSettings"][0]{
  siteTitle,
  companyName,
  domain,
  logo,
  contactLabel,
  referencesTag,
  references[]{
    _key,
    alt,
    image
  },
  navItems[]{
    _key,
    href,
    label
  },
  footerLinks[]{
    _key,
    href,
    label
  },
  footerAddress,
  footerCredit
}`

export const homePageQuery = groq`*[_type == "homePage"][0]{
  heroEyebrow,
  heroTitleLine1,
  heroTitleLine2,
  heroTitleAccent,
  heroSubtitle,
  heroDescription,
  heroPrimaryLabel,
  heroPrimaryHref,
  heroSecondaryLabel,
  heroSecondaryHref,
  heroBackgroundImage,
  heroProductImage,
  heroStats,
  servicesTag,
  servicesTitle,
  servicesDescription,
  services[]{
    _key,
    tag,
    title,
    description,
    buttonLabel,
    buttonHref,
    image,
    imageAlign,
    imageFit
  },
  extrasTag,
  extrasTitle,
  extras,
  aboutTag,
  aboutTitle,
  aboutText,
  aboutImage,
  aboutIcoLabel,
  aboutIcoValue,
  aboutDicLabel,
  aboutDicValue,
  aboutAddressLabel,
  aboutAddressValue,
  ctaTitle,
  ctaText,
  ctaButtonLabel,
  ctaButtonHref
}`

export const palletsPageQuery = groq`*[_type == "palletsPage"][0]${simplePageProjection}`
export const productionPageQuery = groq`*[_type == "productionPage"][0]${simplePageProjection}`
export const devicesPageQuery = groq`*[_type == "devicesPage"][0]${simplePageProjection}`

export const contactPageQuery = groq`*[_type == "contactPage"][0]{
  heroTag,
  heroTitle,
  heroText,
  detailsTitle,
  contactPersonLabel,
  contactPersonValue,
  addressLabel,
  addressValue,
  phoneLabel,
  phoneValue,
  emailLabel,
  emailValue,
  webLabel,
  webValue,
  companyDataTitle,
  companyIco,
  companyDic,
  companyYear,
  formTitle,
  formNameLabel,
  formPhoneLabel,
  formEmailLabel,
  formTopicLabel,
  formMessageLabel,
  formSubmitLabel,
  inquiryOptions
}`

export const productsPageQuery = groq`*[_type == "productsPage"][0]{
  heroEyebrow,
  heroTitle,
  heroAccent,
  heroSubtitle,
  heroDescription,
  heroPrimaryLabel,
  heroPrimaryHref,
  heroSecondaryLabel,
  heroSecondaryHref,
  heroImage,
  heroStats,
  introTag,
  introTitle,
  introParagraphs,
  introImage,
  catalogTag,
  catalogTitle,
  catalogDescription,
  productCatalog[]{
    _key,
    badge,
    title,
    subtitle,
    description,
    image,
    imageAlt,
    highlights,
    documentsTitle,
    documents[]{
      _key,
      label,
      file{
        asset->{
          url,
          originalFilename
        }
      }
    },
    videosTitle,
    videos[]{
      _key,
      youtubeId,
      label
    },
    galleryTitle,
    galleryImages[]{
      _key,
      alt,
      image
    },
    specsTitle,
    specs[]{
      _key,
      parameter,
      value
    }
  },
  efficiencyTitleA,
  efficiencyValueA,
  efficiencyTitleB,
  efficiencyValueB,
  benefitsTag,
  benefitsTitle,
  benefits,
  useCasesTag,
  useCasesTitle,
  useCases[]{
    title,
    description
  },
  dimensionsTag,
  dimensionsTitle,
  dimensionImages[]{
    alt,
    image
  },
  basicSpecs,
  batterySpecs,
  chargingSpecs,
  equipmentGroups,
  rangeTag,
  rangeTitle,
  rangeCards[]{
    title,
    badge,
    badgeClass,
    info,
    image
  },
  accessoriesTag,
  accessoriesTitle,
  accessories[]{
    title,
    description,
    alt,
    image
  },
  certificatesTag,
  certificatesTitle,
  certificates[]{
    title,
    alt,
    image
  },
  galleryTag,
  galleryTitle,
  galleryDescription,
  galleryImages[]{
    alt,
    asset->
  },
  videosTag,
  videosTitle,
  videos[]{
    youtubeId,
    label
  },
  ctaTitle,
  ctaText,
  ctaPrimaryLabel,
  ctaPrimaryHref,
  ctaSecondaryLabel,
  ctaSecondaryHref
}`
